use_frameworks!

platform :ios, '8.0'

target 'PodTestDemo_Example' do
  pod 'PodTestDemo', :path => '../'

  target 'PodTestDemo_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
